### ISSUE TITLE
文章详情页

### ISSUE THREAD

**Issue by Natt7** [uicestone/eBest#20]
一共就两种模式，一种是有tab的一种是没有tab的，现在两种页面错乱。。。。。

**Comment by uicestone** [comment]
具体哪些页面看看？我现在看是对的，昨晚修过了

**Comment by Natt7** [comment]
比如说这个的tab没有了。。
http://ebest.uice.lu/category/solutions/#retail-execution

**Comment by Natt7** [comment]
现在solution的这些详情页tab功能有问题

**Comment by Natt7** [comment]
还是有问题，参考了Direct Store Delivery这篇文章，我把内容直接复制到另一篇文章中这个tab功能还是有问题，但Direct Store Delivery这篇文章是好的。
