### ISSUE TITLE
修改首页大图高度

### ISSUE THREAD

**Issue by Natt7** [uicestone/eBest#21]
修改整体slide高度，减小slide高度，550px左右 适合13寸屏幕一页显示slide内容。

**Comment by uicestone** [comment]
这里求截图

**Comment by Natt7** [comment]
![qq 20150911110131](https://cloud.githubusercontent.com/assets/5966927/9806216/96d7088a-5874-11e5-9113-567a2c3a631c.jpg)

这个屏幕的尺寸应该是1366的

**Comment by Natt7** [comment]
![image](https://cloud.githubusercontent.com/assets/5966927/9830114/826195ce-5954-11e5-9e9f-aa57cf6b4c68.png)
这个屏幕的尺寸是1920*1080的，这里的文案感觉太大了点。
最好是每种屏幕都把文案 more和free trail都现实在一个屏幕内。

**Comment by Natt7** [comment]
这个高度的问题我和客户讨论过了，首页大图上的标题、摘要和more的按钮都去掉吧，要保证free trial的banner在13寸屏幕上能一屏显示，所以需要调整大图的高度，并且可以更换大图图片。
