### ISSUE TITLE
news旁边的视频和news整体适应16：9的宽高比

### ISSUE THREAD

**Issue by Natt7** [uicestone/eBest#23]

**Comment by Natt7** [comment]
首页上，news这个版块和视频是需要能够自动调节高度的，现在写死了，所以当显示器不一致时会导致在视频下部有空白部分。客户这得视频应该都是16：9的，根据这个比例做调整吧。

**Comment by uicestone** [comment]
@rupertqin 首页新闻的区块希望做如下改进:

![image](https://cloud.githubusercontent.com/assets/2181611/9835684/ec87dad2-5a29-11e5-8d24-dcb3ebde1a93.png)
1. 小屏幕（1280宽度）上右侧日期换行
2. 小屏幕下方留有空白（被右侧翻页尖头从垂直方向撑开了）
3. 新闻摘要多行时，整体高度出现问题。应该限制到一行，然后用ellipsis省略，但向右的箭头也会被省略，可以修改一下。

**Comment by Natt7** [comment]
![image](https://cloud.githubusercontent.com/assets/5966927/9837237/3581261c-5a6b-11e5-9145-e2812918d73e.png)
这个是我添加完新闻摘要之后，高度是有点问题。

**Comment by Natt7** [comment]
在视频的下面还是有一块留白的地方，最好是能让下面的网站地图和视频贴合。

**Comment by Natt7** [comment]
![image](https://cloud.githubusercontent.com/assets/5966927/9923895/add03d1a-5d2c-11e5-9b45-2c0ff503f96b.png)
这里的箭头对齐到日期的day这里，摘要的字号和网站地图保持一致。摘要显示的文字可以多一点，但还是保证在一行。

**Comment by uicestone** [comment]
@Natt7 再烦把你变成卫生巾

**Comment by Natt7** [comment]
大哥 一次改好好么。
