### ISSUE TITLE
新闻不能输入摘要

### ISSUE THREAD

**Issue by Natt7** [uicestone/eBest#45]

**Comment by uicestone** [comment]
可以的，在下图位置输入

![image](https://cloud.githubusercontent.com/assets/2181611/9829482/1e9665c2-5938-11e5-88b9-eecf734fdf56.png)

显示效果：

![image](https://cloud.githubusercontent.com/assets/2181611/9829485/2c2c73c0-5938-11e5-91d2-744dd368f630.png)

**Comment by Natt7** [comment]
![image](https://cloud.githubusercontent.com/assets/5966927/9829917/725f326a-594c-11e5-9475-708b2be74259.png)
我这为什么没有呢。。

**Comment by uicestone** [comment]
解决
