### ISSUE TITLE
中文版的云服务中云计算技术文章需要隐藏 和英文的overview一样

### ISSUE THREAD

**Issue by Natt7** [uicestone/eBest#49]

**Comment by Natt7** [comment]
还有网站地图的位置和cloud的列表页的
![image](https://cloud.githubusercontent.com/assets/5966927/9952418/e141c1a6-5e07-11e5-8b9b-352f961d85e4.png)
![image](https://cloud.githubusercontent.com/assets/5966927/9952419/e4b0d4c6-5e07-11e5-9d4e-854e63c36433.png)

**Comment by uicestone** [comment]
这都被发现了……
