### ISSUE TITLE
产品和云服务列表页添加视频 中英文版都是

### ISSUE THREAD

**Issue by Natt7** [uicestone/eBest#53]
![image](https://cloud.githubusercontent.com/assets/5966927/9990461/218526e8-6094-11e5-9181-04f50703aef5.png)

**Comment by uicestone** [comment]
和首页视频一样，创建一个文章，在其中仅插入一个视频，并设置封面图片。

标签为：Cloud Video 或 Products Video

封面图片尺寸为：958x514或等比例缩放（与右侧图片大小一致）
