### ISSUE TITLE
首页矩阵链接和动态化简介

### ISSUE THREAD

**Issue by uicestone** [uicestone/eBest#7]

**Comment by Natt7** [comment]
这边应该都是对应的链接到service的内容里

**Comment by Natt7** [comment]
应该链接到一个solution页面 但其实首页和导航上都没有solution 我和客户确认一下

**Comment by Natt7** [comment]
需要新建一个solution的详情页，但这个页面在首页上没有导航，我和客户确认过了

**Comment by uicestone** [comment]
样子跟Cloud的详情一样？

**Comment by Natt7** [comment]
嗯 对的 和cloud product详情页一样
