### ISSUE TITLE
缩短中文版文章的url

### ISSUE THREAD

**Issue by Natt7** [uicestone/eBest#75]
现有的文章url为文章标题，seo优化希望：
不需要中文的URL 我们需要英文的，而且简短一点的。中文URL百度不会收录抓取

**Comment by uicestone** [comment]
目前只有新闻的URL是包含中文标题的，可以通过在发布新闻的时候修改“固定链接”中的名称实现。

![image](https://cloud.githubusercontent.com/assets/2181611/14037002/0353f212-f27a-11e5-8575-edbad4fcdc5d.png)
